frase = str(input('Digite seu nome completo para eu analisar essa merda ')).strip()
frase1 = frase.upper()
print(frase1)
frase2 = frase1.lower()
print(frase2)
print('Seu nome tem {} letras '.format(len(frase)-frase.count(' ')))
separa = frase.split()
print('Seu primeiro nome é {} e tem {} letras '.format(separa[0], len(separa[0])))
